export const CARDS = [
  {
    name: "THAILAND",
    slug: "thailand",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TH.avif?q=60&v=1",
    code: "th",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "17 Aug 2026, 11:51 AM"
  },
  {
    name: "UNITED ARAB EMIRATES",
    slug: "united-arab-emirates",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AE.avif?q=60&v=1",
    code: "ae",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: "₹8,049",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Aug 2026, 10:47 AM"
  },
  {
    name: "SRI LANKA",
    slug: "sri-lanka",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LK.avif?q=60&v=1",
    code: "lk",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "18 Aug 2026, 10:30 AM"
  },
  {
    name: "MALAYSIA",
    slug: "malaysia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MY.avif?q=60&v=1",
    code: "my",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: "17 Aug 2026, 11:03 AM"
  },
  {
    name: "VIETNAM",
    slug: "vietnam",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/VN.avif?q=60&v=1",
    code: "vn",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹4,100",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "24 Aug 2026, 11:25 PM"
  },
  {
    name: "INDONESIA",
    slug: "indonesia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ID.avif?q=60&v=1",
    code: "id",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹3,324",
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Aug 2026, 11:01 AM"
  },
  {
    name: "UNITED STATES",
    slug: "united-states",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/US.avif?q=60&v=1",
    code: "us",
    type: "STICKER",
    valid: "10 YEARS",
    fees: "₹18,200",
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "14 Oct 2026, 11:24 AM"
  },
  {
    name: "HONG KONG SAR CHINA",
    slug: "hong-kong-sar-china",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/HK.avif?q=60&v=1",
    code: "hk",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: "₹996",
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "18 Aug 2026, 11:07 AM"
  },
  {
    name: "JAPAN",
    slug: "japan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/JP.avif?q=60&v=1",
    code: "jp",
    type: "STICKER",
    valid: "90 DAYS",
    fees: "₹3,750",
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "1 Sep 2026, 9:52 PM"
  },
  {
    name: "MALDIVES",
    slug: "maldives",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MV.avif?q=60&v=1",
    code: "mv",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "17 Aug 2026, 2:10 PM"
  },
  {
    name: "EGYPT",
    slug: "egypt",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/EG.avif?q=60&v=1",
    code: "eg",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹4,200",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "20 Aug 2026, 10:54 PM"
  },
  {
    name: "MAURITIUS",
    slug: "mauritius",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MU.avif?q=60&v=1",
    code: "mu",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Passport",
    emergencyAssistance: true,
    guaranteedDate: "17 Aug 2026, 2:10 PM"
  },
  {
    name: "CHINA",
    slug: "china",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CN.avif?q=60&v=1",
    code: "cn",
    type: "STICKER",
    valid: "90 DAYS",
    fees: "₹13,700",
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "12 Oct 2026, 9:39 PM"
  },
  {
    name: "SOUTH AFRICA",
    slug: "south-africa",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ZA.avif?q=60&v=1",
    code: "za",
    type: "E-VISA",
    valid: "1 YEARS",
    fees: "₹2,991",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "20 Aug 2026, 11:36 PM"
  },
  {
    name: "UNITED KINGDOM",
    slug: "united-kingdom",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GB.avif?q=60&v=1",
    code: "gb",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: "₹23,168",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "24 Sep 2026, 11:02 AM"
  },
  {
    name: "GEORGIA",
    slug: "georgia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GE.avif?q=60&v=1",
    code: "ge",
    type: "E-VISA",
    valid: "120 DAYS",
    fees: "₹5,500",
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "26 Aug 2026, 11:02 AM"
  },
  {
    name: "OMAN",
    slug: "oman",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/OM.avif?q=60&v=1",
    code: "om",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹2,640",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Aug 2026, 11:17 PM"
  },
  {
    name: "SOUTH KOREA",
    slug: "south-korea",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KR.avif?q=60&v=1",
    code: "kr",
    type: "STICKER",
    valid: "90 DAYS",
    fees: "₹9,143",
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "8 Sep 2026, 9:54 PM"
  },
  {
    name: "AZERBAIJAN",
    slug: "azerbaijan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AZ.avif?q=60&v=1",
    code: "az",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹5,000",
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: "21 Aug 2026, 8:28 AM"
  },
  {
    name: "FRANCE",
    slug: "france",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/FR.avif?q=60&v=1",
    code: "fr",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹7,410",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Sep 2026, 12:00 AM"
  },
  {
    name: "AUSTRALIA",
    slug: "australia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AU.avif?q=60&v=1",
    code: "au",
    type: "E-VISA",
    valid: "6 MONTHS",
    fees: "₹22,200",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "27 Aug 2026, 11:27 AM"
  },
  {
    name: "SWITZERLAND",
    slug: "switzerland",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CH.avif?q=60&v=1",
    code: "ch",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹8,090",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Sep 2026, 12:00 AM"
  },
  {
    name: "KENYA",
    slug: "kenya",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KE.avif?q=60&v=1",
    code: "ke",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹4,700",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Aug 2026, 11:15 AM"
  },
  {
    name: "RUSSIA",
    slug: "russia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/RU.avif?q=60&v=1",
    code: "ru",
    type: "E-VISA",
    valid: "120 DAYS",
    fees: "₹9,700",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "25 Aug 2026, 11:29 PM"
  },
  {
    name: "TÜRKIYE",
    slug: "türkiye",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TR.avif?q=60&v=1",
    code: "tr",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: "₹7,850",
    documentsNeeded: "Passport, US/UK/Schengen Visa",
    emergencyAssistance: true,
    guaranteedDate: "19 Aug 2026, 10:49 AM"
  },
  {
    name: "SPAIN",
    slug: "spain",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ES.avif?q=60&v=1",
    code: "es",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹6,840",
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Sep 2026, 12:00 AM"
  },
  {
    name: "UZBEKISTAN",
    slug: "uzbekistan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/UZ.avif?q=60&v=1",
    code: "uz",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹3,050",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "26 Aug 2026, 11:35 AM"
  },
  {
    name: "QATAR",
    slug: "qatar",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/QA.avif?q=60&v=1",
    code: "qa",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹2,150",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "22 Aug 2026, 11:26 AM"
  },
  {
    name: "GERMANY",
    slug: "germany",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/DE.avif?q=60&v=1",
    code: "de",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹6,796",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "24 Sep 2026, 12:00 AM"
  },
  {
    name: "ITALY",
    slug: "italy",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/IT.avif?q=60&v=1",
    code: "it",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹5,530",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "20 Sep 2026, 12:00 AM"
  },
  {
    name: "TAIWAN",
    slug: "taiwan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TW.avif?q=60&v=1",
    code: "tw",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹1,000",
    documentsNeeded: "Passport, US/UK/Schengen Visa",
    emergencyAssistance: true,
    guaranteedDate: "18 Aug 2026, 11:33 AM"
  },
  {
    name: "GREECE",
    slug: "greece",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GR.avif?q=60&v=1",
    code: "gr",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹6,890",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Sep 2026, 12:00 AM"
  },
  {
    name: "NETHERLANDS",
    slug: "netherlands",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/NL.avif?q=60&v=1",
    code: "nl",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹6,690",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "29 Sep 2026, 12:00 AM"
  },
  {
    name: "SAUDI ARABIA",
    slug: "saudi-arabia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SA.avif?q=60&v=1",
    code: "sa",
    type: "E-VISA",
    valid: "1 YEARS",
    fees: "₹14,668",
    documentsNeeded: "Photo, Passport, US/UK/Schengen Visa",
    emergencyAssistance: true,
    guaranteedDate: "24 Aug 2026, 11:40 AM"
  },
  {
    name: "TANZANIA",
    slug: "tanzania",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TZ.avif?q=60&v=1",
    code: "tz",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹7,500",
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: "27 Aug 2026, 11:43 AM"
  },
  {
    name: "NEW ZEALAND",
    slug: "new-zealand",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/NZ.avif?q=60&v=1",
    code: "nz",
    type: "E-VISA",
    valid: "1 YEARS",
    fees: "₹30,550",
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "31 Aug 2026, 10:55 AM"
  },
  {
    name: "MONGOLIA",
    slug: "mongolia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MN.avif?q=60&v=1",
    code: "mn",
    type: "E-VISA",
    valid: "120 DAYS",
    fees: "₹1,350",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "22 Aug 2026, 10:53 AM"
  },
  {
    name: "MEXICO",
    slug: "mexico",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MX.avif?q=60&v=1",
    code: "mx",
    type: "STICKER",
    valid: "180 DAYS",
    fees: "₹5,000",
    documentsNeeded: "Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "3 Sep 2026, 10:53 AM"
  },
  {
    name: "CAMBODIA",
    slug: "cambodia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KH.avif?q=60&v=1",
    code: "kh",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹4,300",
    documentsNeeded: "Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "28 Aug 2026, 10:49 AM"
  },
  {
    name: "AUSTRIA",
    slug: "austria",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AT.avif?q=60&v=1",
    code: "at",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹7,491",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "13 Sep 2026, 12:00 AM"
  },
  {
    name: "PHILIPPINES",
    slug: "philippines",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/PH.avif?q=60&v=1",
    code: "ph",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹7,740",
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "2 Sep 2026, 11:41 AM"
  },
  {
    name: "FINLAND",
    slug: "finland",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/FI.avif?q=60&v=1",
    code: "fi",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹7,613",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "26 Sep 2026, 12:00 AM"
  },
  {
    name: "IRELAND",
    slug: "ireland",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/IE.avif?q=60&v=1",
    code: "ie",
    type: "STICKER",
    valid: "90 DAYS",
    fees: "₹14,000",
    documentsNeeded: "Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "1 Sep 2026, 11:28 AM"
  },
  {
    name: "JORDAN",
    slug: "jordan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/JO.avif?q=60&v=1",
    code: "jo",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹7,513",
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: "18 Aug 2026, 11:31 PM"
  },
  {
    name: "ZIMBABWE",
    slug: "zimbabwe",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ZW.avif?q=60&v=1",
    code: "zw",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹5,450",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "18 Aug 2026, 12:00 PM"
  },
  {
    name: "ARMENIA",
    slug: "armenia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AM.avif?q=60&v=1",
    code: "am",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: "₹1,750",
    documentsNeeded: "Photo, Passport, US/UK/Schengen Visa",
    emergencyAssistance: true,
    guaranteedDate: "25 Aug 2026, 10:31 AM"
  },
  {
    name: "LAOS",
    slug: "laos",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LA.avif?q=60&v=1",
    code: "la",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: "₹6,863",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "21 Aug 2026, 10:50 AM"
  },
  {
    name: "CANADA",
    slug: "canada",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CA.avif?q=60&v=1",
    code: "ca",
    type: "STICKER",
    valid: "10 YEARS",
    fees: "₹20,600",
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport, US/UK/Schengen Visa",
    emergencyAssistance: true,
    guaranteedDate: "19 Nov 2026, 10:34 AM"
  },
  {
    name: "BANGLADESH",
    slug: "bangladesh",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BD.avif?q=60&v=1",
    code: "bd",
    type: "STICKER",
    valid: "90 DAYS",
    fees: "₹2,500",
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: "29 Aug 2026, 9:37 PM"
  },
  {
    name: "PORTUGAL",
    slug: "portugal",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/PT.avif?q=60&v=1",
    code: "pt",
    type: "STICKER",
    valid: "2 YEARS",
    fees: "₹8,167",
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: "19 Sep 2026, 12:00 AM"
  },
  {
    name: "CZECHIA",
    slug: "czechia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CZ.avif?q=60&v=1",
    code: "cz",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MOROCCO",
    slug: "morocco",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MA.avif?q=60&v=1",
    code: "ma",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ETHIOPIA",
    slug: "ethiopia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ET.avif?q=60&v=1",
    code: "et",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ZAMBIA",
    slug: "zambia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ZM.avif?q=60&v=1",
    code: "zm",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "KYRGYZSTAN",
    slug: "kyrgyzstan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KG.avif?q=60&v=1",
    code: "kg",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "UGANDA",
    slug: "uganda",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/UG.avif?q=60&v=1",
    code: "ug",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "KUWAIT",
    slug: "kuwait",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KW.avif?q=60&v=1",
    code: "kw",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ISRAEL",
    slug: "israel",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/IL.avif?q=60&v=1",
    code: "il",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BAHRAIN",
    slug: "bahrain",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BH.avif?q=60&v=1",
    code: "bh",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "TAJIKISTAN",
    slug: "tajikistan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TJ.avif?q=60&v=1",
    code: "tj",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MADAGASCAR",
    slug: "madagascar",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MG.avif?q=60&v=1",
    code: "mg",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MOLDOVA",
    slug: "moldova",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MD.avif?q=60&v=1",
    code: "md",
    type: "STICKER",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport, US/UK/Schengen Visa",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SOUTH SUDAN",
    slug: "south-sudan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SS.avif?q=60&v=1",
    code: "ss",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MALTA",
    slug: "malta",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MT.avif?q=60&v=1",
    code: "mt",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "VENEZUELA",
    slug: "venezuela",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/VE.avif?q=60&v=1",
    code: "ve",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SWEDEN",
    slug: "sweden",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SE.avif?q=60&v=1",
    code: "se",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "URUGUAY",
    slug: "uruguay",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/UY.avif?q=60&v=1",
    code: "uy",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "NAMIBIA",
    slug: "namibia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/NA.avif?q=60&v=1",
    code: "na",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ARGENTINA",
    slug: "argentina",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AR.avif?q=60&v=1",
    code: "ar",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "BAHAMAS",
    slug: "bahamas",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BS.avif?q=60&v=1",
    code: "bs",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "PAPUA NEW GUINEA",
    slug: "papua-new-guinea",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/PG.avif?q=60&v=1",
    code: "pg",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ANTIGUA & BARBUDA",
    slug: "antigua-&-barbuda",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AG.avif?q=60&v=1",
    code: "ag",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BRUNEI",
    slug: "brunei",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BN.avif?q=60&v=1",
    code: "bn",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ICELAND",
    slug: "iceland",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/IS.avif?q=60&v=1",
    code: "is",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BRAZIL",
    slug: "brazil",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BR.avif?q=60&v=1",
    code: "br",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BELGIUM",
    slug: "belgium",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BE.avif?q=60&v=1",
    code: "be",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "HUNGARY",
    slug: "hungary",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/HU.avif?q=60&v=1",
    code: "hu",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CROATIA",
    slug: "croatia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/HR.avif?q=60&v=1",
    code: "hr",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BHUTAN",
    slug: "bhutan",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BT.avif?q=60&v=1",
    code: "bt",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "POLAND",
    slug: "poland",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/PL.avif?q=60&v=1",
    code: "pl",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BULGARIA",
    slug: "bulgaria",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BG.avif?q=60&v=1",
    code: "bg",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ESTONIA",
    slug: "estonia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/EE.avif?q=60&v=1",
    code: "ee",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SLOVAKIA",
    slug: "slovakia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SK.avif?q=60&v=1",
    code: "sk",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "COLOMBIA",
    slug: "colombia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CO.avif?q=60&v=1",
    code: "co",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "LUXEMBOURG",
    slug: "luxembourg",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LU.avif?q=60&v=1",
    code: "lu",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CUBA",
    slug: "cuba",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CU.avif?q=60&v=1",
    code: "cu",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SLOVENIA",
    slug: "slovenia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SI.avif?q=60&v=1",
    code: "si",
    type: "STICKER",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SEYCHELLES",
    slug: "seychelles",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SC.avif?q=60&v=1",
    code: "sc",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "LATVIA",
    slug: "latvia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LV.avif?q=60&v=1",
    code: "lv",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BENIN",
    slug: "benin",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BJ.avif?q=60&v=1",
    code: "bj",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "BURKINA FASO",
    slug: "burkina-faso",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BF.avif?q=60&v=1",
    code: "bf",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ALGERIA",
    slug: "algeria",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/DZ.avif?q=60&v=1",
    code: "dz",
    type: "STICKER",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "LITHUANIA",
    slug: "lithuania",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LT.avif?q=60&v=1",
    code: "lt",
    type: "STICKER",
    valid: "2 YEARS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ANGUILLA",
    slug: "anguilla",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/AI.avif?q=60&v=1",
    code: "ai",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CAMEROON",
    slug: "cameroon",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CM.avif?q=60&v=1",
    code: "cm",
    type: "E-VISA",
    valid: "15 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MALAWI",
    slug: "malawi",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MW.avif?q=60&v=1",
    code: "mw",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CONGO - BRAZZAVILLE",
    slug: "congo---brazzaville",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CG.avif?q=60&v=1",
    code: "cg",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "GHANA",
    slug: "ghana",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GH.avif?q=60&v=1",
    code: "gh",
    type: "STICKER",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MOZAMBIQUE",
    slug: "mozambique",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MZ.avif?q=60&v=1",
    code: "mz",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "GABON",
    slug: "gabon",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GA.avif?q=60&v=1",
    code: "ga",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ECUADOR",
    slug: "ecuador",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/EC.avif?q=60&v=1",
    code: "ec",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "TUNISIA",
    slug: "tunisia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TN.avif?q=60&v=1",
    code: "tn",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "TOGO",
    slug: "togo",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TG.avif?q=60&v=1",
    code: "tg",
    type: "E-VISA",
    valid: "15 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "GUINEA",
    slug: "guinea",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GN.avif?q=60&v=1",
    code: "gn",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CONGO - KINSHASA",
    slug: "congo---kinshasa",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CD.avif?q=60&v=1",
    code: "cd",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "EQUATORIAL GUINEA",
    slug: "equatorial-guinea",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GQ.avif?q=60&v=1",
    code: "gq",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CHILE",
    slug: "chile",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CL.avif?q=60&v=1",
    code: "cl",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "NIGERIA",
    slug: "nigeria",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/NG.avif?q=60&v=1",
    code: "ng",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "RWANDA",
    slug: "rwanda",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/RW.avif?q=60&v=1",
    code: "rw",
    type: "E-VISA",
    valid: "30 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SIERRA LEONE",
    slug: "sierra-leone",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SL.avif?q=60&v=1",
    code: "sl",
    type: "E-VISA",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "GUATEMALA",
    slug: "guatemala",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GT.avif?q=60&v=1",
    code: "gt",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SOMALIA",
    slug: "somalia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SO.avif?q=60&v=1",
    code: "so",
    type: "E-VISA",
    valid: "180 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ESWATINI",
    slug: "eswatini",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SZ.avif?q=60&v=1",
    code: "sz",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "CÔTE D’IVOIRE",
    slug: "côte-d’ivoire",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CI.avif?q=60&v=1",
    code: "ci",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "DJIBOUTI",
    slug: "djibouti",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/DJ.avif?q=60&v=1",
    code: "dj",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "LIBERIA",
    slug: "liberia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LR.avif?q=60&v=1",
    code: "lr",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "HONDURAS",
    slug: "honduras",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/HN.avif?q=60&v=1",
    code: "hn",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "CHAD",
    slug: "chad",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TD.avif?q=60&v=1",
    code: "td",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "DOMINICAN REPUBLIC",
    slug: "dominican-republic",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/DO.avif?q=60&v=1",
    code: "do",
    type: "STICKER",
    valid: "60 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "ERITREA",
    slug: "eritrea",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ER.avif?q=60&v=1",
    code: "er",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Income Tax Returns, Bank Statements, Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "SÃO TOMÉ & PRÍNCIPE",
    slug: "são-tomé-&-príncipe",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ST.avif?q=60&v=1",
    code: "st",
    type: "E-VISA",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "MALI",
    slug: "mali",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/ML.avif?q=60&v=1",
    code: "ml",
    type: "STICKER",
    valid: "90 DAYS",
    fees: null,
    documentsNeeded: "Photo, Passport",
    emergencyAssistance: true,
    guaranteedDate: null
  },
  {
    name: "BELARUS",
    slug: "belarus",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BY.avif?q=60&v=1",
    code: "by",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "MACAO SAR CHINA",
    slug: "macao-sar-china",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MO.avif?q=60&v=1",
    code: "mo",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "NEPAL",
    slug: "nepal",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/NP.avif?q=60&v=1",
    code: "np",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "FIJI",
    slug: "fiji",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/FJ.avif?q=60&v=1",
    code: "fj",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "ST. LUCIA",
    slug: "st.-lucia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/LC.avif?q=60&v=1",
    code: "lc",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "BRITISH VIRGIN ISLANDS",
    slug: "british-virgin-islands",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/VG.avif?q=60&v=1",
    code: "vg",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "PALAU",
    slug: "palau",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/PW.avif?q=60&v=1",
    code: "pw",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "BARBADOS",
    slug: "barbados",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BB.avif?q=60&v=1",
    code: "bb",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "SAMOA",
    slug: "samoa",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/WS.avif?q=60&v=1",
    code: "ws",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "JAMAICA",
    slug: "jamaica",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/JM.avif?q=60&v=1",
    code: "jm",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "MICRONESIA",
    slug: "micronesia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/FM.avif?q=60&v=1",
    code: "fm",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "BURUNDI",
    slug: "burundi",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/BI.avif?q=60&v=1",
    code: "bi",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "COOK ISLANDS",
    slug: "cook-islands",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/CK.avif?q=60&v=1",
    code: "ck",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "EL SALVADOR",
    slug: "el-salvador",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SV.avif?q=60&v=1",
    code: "sv",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "MAURITANIA",
    slug: "mauritania",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MR.avif?q=60&v=1",
    code: "mr",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "TURKS & CAICOS ISLANDS",
    slug: "turks-&-caicos-islands",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TC.avif?q=60&v=1",
    code: "tc",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "MONTSERRAT",
    slug: "montserrat",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MS.avif?q=60&v=1",
    code: "ms",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "MARSHALL ISLANDS",
    slug: "marshall-islands",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/MH.avif?q=60&v=1",
    code: "mh",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "TRINIDAD & TOBAGO",
    slug: "trinidad-&-tobago",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/TT.avif?q=60&v=1",
    code: "tt",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "DOMINICA",
    slug: "dominica",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/DM.avif?q=60&v=1",
    code: "dm",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "COMOROS",
    slug: "comoros",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KM.avif?q=60&v=1",
    code: "km",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "SOLOMON ISLANDS",
    slug: "solomon-islands",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SB.avif?q=60&v=1",
    code: "sb",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "SENEGAL",
    slug: "senegal",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/SN.avif?q=60&v=1",
    code: "sn",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "RÉUNION",
    slug: "réunion",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/RE.avif?q=60&v=1",
    code: "re",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "ST. KITTS & NEVIS",
    slug: "st.-kitts-&-nevis",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/KN.avif?q=60&v=1",
    code: "kn",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "ST. VINCENT & GRENADINES",
    slug: "st.-vincent-&-grenadines",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/VC.avif?q=60&v=1",
    code: "vc",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "GUINEA-BISSAU",
    slug: "guinea-bissau",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GW.avif?q=60&v=1",
    code: "gw",
    type: "VISA ON ARRIVAL",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "NIUE",
    slug: "niue",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/NU.avif?q=60&v=1",
    code: "nu",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "HAITI",
    slug: "haiti",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/HT.avif?q=60&v=1",
    code: "ht",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  },
  {
    name: "GAMBIA",
    slug: "gambia",
    image: "https://media.atlys.com/w_400/b2c/Home%20page/country-bg-gradient/GM.avif?q=60&v=1",
    code: "gm",
    type: "VISA FREE",
    valid: null,
    fees: null,
    documentsNeeded: null,
    emergencyAssistance: false,
    guaranteedDate: null
  }
];
